### ISSUE TITLE
Should CKFinder command work without Image plugin

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5-ckfinder#48]
The `CKFinderCommand` expects both `'link'` and `'imageUpload'` commands to be present:

https://github.com/ckeditor/ckeditor5-ckfinder/blob/0f941b00aed5fc6462cabfebba12ee0c9de522e0/src/ckfindercommand.js#L45

but it probably could work without the image plugin as a link only solution (or insert image only).

**Comment by Reinmar** [comment]
I guess it should. But we need then error messages (notifications) for the user why inserting e.g. an image didn't work.

OTOH, was this ever requested by someone?

**Comment by jodator** [comment]
> OTOH, was this ever requested by someone?

nope - I've just found it when checking this: https://github.com/ckeditor/ckeditor5-vue/issues/89.

**Comment by Reinmar** [comment]
@Mgsy confirms that this issue appears from time to time. So, the minimum would be to mention that in the documentation.

BTW, I also realised that relying on imageUpload command's state doesn't make much sense because the upload could've been done in the CKFinder manager. And then you just need to insert the image via URL into the content. Which should also happen via a command. And the state of this command matters. How does it work right now?

**Comment by jodator** [comment]
OMG.. we're using `insertImage` to insert image (which is OK) but we check `imageUpload` command state... (which is :man_facepalming:).

https://github.com/ckeditor/ckeditor5-ckfinder/blob/63ac6d1ac29664e45c171b8f9eea9f2691f69fc7/src/ckfindercommand.js#L41

https://github.com/ckeditor/ckeditor5-ckfinder/blob/63ac6d1ac29664e45c171b8f9eea9f2691f69fc7/src/ckfindercommand.js#L142

I'd do it ASAP as those are some small fixes to address.
